name: Publish Pages

on:
  push:
    branches: [main]

jobs:
  Test:
    uses: brendanjmeade/celeri_ui/.github/workflows/test.yml@main
  CodeQl:
    uses: brendanjmeade/celeri_ui/.github/workflows/codeql-analysis.yml@main

  Publish:
    runs-on: ubuntu-latest
    needs:
      - Test
      - CodeQl

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
        env:
          VITE_MAPBOX_TOKEN: ${{ secrets.CELERI_MAPBOX_TOKEN }}

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '${{ steps.mdbook-version.outputs.MDBOOK_VERSION }}'

      - name: Build Docs
        run: npm run docs:build

      - run: cp -R ./docs/book ./dist/public/docs

      - run: echo "" > ./dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
