name: Test

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Validate
        run: npm run lint test:ci
        env:
          VITE_MAPBOX_TOKEN: ${{ secrets.CELERI_MAPBOX_TOKEN }}
